ADD: CONDITION

diff --git a/.github/workflows/myworkflow.yaml b/.github/workflows/myworkflow.yaml
--- a/.github/workflows/myworkflow.yaml
+++ b/.github/workflows/myworkflow.yaml
@@ -61,7 +61,12 @@ jobs:
         image-ref: 'kericccccc/cicd:${{ github.sha }}'     
         format: 'table'
         output: './trivy-report.json'
-        # ignore-unfixed: true
+      
+    - name: Check Trivy scan result
+      run: |
+        if grep -q '"CRITICAL"' ./trivy-report.json; then
+          exit 1  # Failure if CRITICAL vulnerabilities found
+        fi
 
     # - name: Convert to table
     #   uses: aquasecurity/trivy-action@master
@@ -81,6 +86,7 @@ jobs:
         retention-days: 20 # 90 is the default
     
     - name: Slack Notification - Failure
+      if: ${{ failure() }}
       uses: rtCamp/action-slack-notify@v2
       env:
         SLACK_COLOR: 'failure'
@@ -94,6 +100,7 @@ jobs:
         initial_comment: 'Scan report by Xia Tian'
 
     - name: Slack Notification - Success
+      if: ${{ success() }}
       uses: rtCamp/action-slack-notify@v2
       env:
         SLACKIFY_MARKDOWN: 'true'
